# testbench
lenet_tb.v
sram_model/SRAM_activation_1024x32b.v
sram_model/SRAM_weight_16384x32b.v

# netlist generated by Design Compiler
../syn/netlist/lenet_syn.v
# Logic Gate models
-v /home/m110/m110061644/synopsys_tech_file/tsmc090.v

+define+GATESIM
+access+r
